appName: myhelmapp

port: 80

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'
    token: 'This would be the token'

image:
  name: registry.gitlab.com/cloudnative20031/infra/sib-admission-controller/k8s-admission-controller
  tag: 0.0.1-SNAPSHOT
  pullSecrets:
    -name: docker-reg-gitlab