appName: myhelmapp

port: 80

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

namespace: bdemers

image:
  sibToken: eyJraWQiOiIxMjM0LTQzMjEtMDAwMCIsImFsZyI6IlJTNTEyIn0.eyJ2Y3MiOnsiYnJhbmNoIjoibWFzaW4iLCJyZXZpc2lvbiI6Imhhc2gtb2YtaW1hZ2UtcmVwbyIsInJlcG9zaXRvcnkiOiJodHRwczovL2dpdGh1Yi5jb20vYmV4YW1wbGUvcHJvamVjdC5naXQifSwiYnVpbGRTY2FuVXJsIjoiaHR0cHM6Ly9kZXZlbG9jaXR5LnNkbGMtZGVtby5ncmFkbGUuY29tL3MvMTIzNDU2Nzg5IiwiYmluYXJ5VXJsIjoiZGV2b3Bzam91cm5leTEvbXl3ZWJhcHA6bGF0ZXN0IiwiaXNzIjoiaHR0cHM6Ly9kZXZlbG9jaXR5LnNkbGMtZGVtby5ncmFkbGUuY29tIiwic3ViIjoiaHR0cHM6Ly9kZXZlbG9jaXR5LnNkbGMtZGVtby5ncmFkbGUuY29tL3MvMTIzNDU2Nzg5IiwiaWF0IjoxNzI5ODc0MjczfQ.j3F_fOMPbZPkGYZBEw8sW3WIKnDFM4UUT1FoNt0Jpt1dgIR9lTpQLKTtJTGnZe7zbuiWEZw4WzgHCV6XEZryeO6OciLiPojEnM-CuhnuXdjgalVJWTLP153cThE8JuGQYpq-Xe2xkM3K90F5Hw1a3Hxl3r3nSQRHPMuFT4x5JCJPPAda7yooZA0oFPfqMWXlzLV44kRoDSSy5nyDrmY0SFnXYTrxNSMYqvrlMKPS1ttHLzwiOBWukpoCqkLYfy8u_YJyfjz3esLXF6Bdvbt5VCRFiI6H5C1OL-YiJLG9dhl_OIR-Ook1VP3b8QTScOOXj-5YVBismOiqWBBtQI1P_g_ePNXEjTi5SoXMcrshS6C2YItKHAnT87q-1jHY6raZggOhta3k__RB_AXleq4uts9Wxviav4KnukmUabR1EKlcggbIf9K6MREsEE_ThfZoiDjbVYrjx2cycWG-nQnR2zLVjljWFfaRFUBj2ETj-NoF-SUIQUGkRQNrvEf-Zosiq2mFf3_-VWmBhRu4ddTPFfkmrLcIfC5RQ8uD_laXQvfKAAyOelP_aIbu6IEN3yIOmOzF74glAtHqWjdio_Efmho9T88L6wtP5AIkbjN43sUr4IVV72tp9FPDg_USnLEvX1Vo48CtugD_zlCaifIj3lOn5lPLiwdepfGPnYzVH3s
  name: replaced-with-token-value
  tag: replaced-with-token-value
#  name: registry.gitlab.com/cloudnative20031/infra/sib-admission-controller/k8s-admission-controller
#  tag: 0.0.1-SNAPSHOT
  pullSecrets:
    - docker-reg-gitlab