apiVersion: batch/v1
kind: Job
metadata:
  generateName: validate-jwt-{{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["false"]
      restartPolicy: Never
  backoffLimit: 1
